
title: Electron - Development Blog
email: nitingoswami473@gmail.com
description: >-

baseurl: ""
url: "https://electron.iamharsh.design/"

github_username:  theuitown
remote_theme: b2a3e8/jekyll-theme-console
# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed

header_pages:
  - about.md

style: dark

footer: 'follow us on <a href="https://instagram.com/iamharsh.dev">instagram</a>'
